[package]
name = "xtask"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
nits-protocol-fixtures = { workspace = true }
nits-client-core-fixtures = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
