// `moor_client_core::Action`: what the UI dispatches to the host.

open Ids

@@warning("-27")
@schema @tag("type")
type t =
  | @as("Connect") Connect({})
  | @as("Disconnect") Disconnect({})
  | @as("ListReviews") ListReviews({@as("workspace_id") workspaceId: workspaceId})
  | @as("OpenReview") OpenReview({@as("review_id") reviewId: reviewId})
  | @as("CloseReview") CloseReview({})
  | @as("DraftOpened") DraftOpened({anchor: Domain.Anchor.t})
  | @as("DraftSubmitted") DraftSubmitted({body: string})
  | @as("DraftDiscarded") DraftDiscarded({})
  | @as("ReplyOpened") ReplyOpened({@as("thread_id") threadId: threadId})
  | @as("SetFocus") SetFocus({focus: View.Focus.t})
  | @as("ToggleHelp") ToggleHelp({})
  | @as("Reply") Reply({@as("thread_id") threadId: threadId, body: string})
  | @as("EditComment") EditComment({@as("comment_id") commentId: commentId, body: string})
  | @as("DeleteComment") DeleteComment({@as("comment_id") commentId: commentId})
  | @as("ResolveThread") ResolveThread({@as("thread_id") threadId: threadId})
  | @as("UnresolveThread") UnresolveThread({@as("thread_id") threadId: threadId})
  | @as("Viewport")
  Viewport({file: View.FileRef.t, @as("first_row") firstRow: int, @as("last_row") lastRow: int})
  | @as("CloseFile") CloseFile({})
  | @as("ToggleDir") ToggleDir({@as("repo_id") repoId: repoId, path: @s.null option<string>})
  | @as("FileSearch") FileSearch({query: @s.null option<string>})
  | @as("SetLayout") SetLayout({layout: View.Layout.t})
  | @as("SetRenderOpts")
  SetRenderOpts({@as("ignore_whitespace") ignoreWhitespace: bool, @as("context_lines") contextLines: int})
  | @as("MarkViewed") MarkViewed({file: View.FileRef.t})
  | @as("UnmarkViewed") UnmarkViewed({file: View.FileRef.t})
  | @as("ListCommits") ListCommits({@as("repo_id") repoId: repoId})
  | @as("StepCommit") StepCommit({selected: @s.null option<int>})
@@warning("+27")
