#!/usr/bin/env bash
# Render an AUR PKGBUILD and .SRCINFO for a released binary.
#
#   render-pkgbuild.sh <package> <version> <tag> <artifact-dir> <out-dir>
#
# We publish the `-bin` flavour: the AUR package installs the tarball we already
# built and signed rather than recompiling, so it can never drift from the
# GitHub release. .SRCINFO is written directly (makepkg is not available on the
# runner) and must stay in step with the PKGBUILD above it.
set -euo pipefail

package=${1:?package}
version=${2:?version}
tag=${3:?tag}
artifacts=${4:?artifact directory}
outdir=${5:?output directory}

repo=https://github.com/JonoPrest/nits
pkgname="$package-bin"
mkdir -p "$outdir"

case $package in
  nits)     pkgdesc="Daemon-backed code review tool where nits stick to content, not diffs" ;;
  nitsd)    pkgdesc="Nits code-review daemon" ;;
  nits-mcp) pkgdesc="MCP stdio server for the Nits code-review daemon" ;;
  *)        echo "unknown package $package" >&2; exit 1 ;;
esac

sha256_for() {
  local file
  file=$(find "$artifacts" -name "$package-$version-$1.tar.gz.sha256" -print -quit)
  [ -n "$file" ] || { echo "no checksum for $1 in $artifacts" >&2; exit 1; }
  awk '{print $1}' "$file"
}

# Arch ships glibc, so the gnu tarballs are the right ones here.
sha_x86=$(sha256_for x86_64-unknown-linux-gnu)
sha_arm=$(sha256_for aarch64-unknown-linux-gnu)
url_x86="$repo/releases/download/$tag/$package-$version-x86_64-unknown-linux-gnu.tar.gz"
url_arm="$repo/releases/download/$tag/$package-$version-aarch64-unknown-linux-gnu.tar.gz"

cat > "$outdir/PKGBUILD" <<EOF
# Generated by scripts/render-pkgbuild.sh — do not edit by hand.
# Maintainer: Jono Prest <jjprest@gmail.com>
pkgname=$pkgname
pkgver=$version
pkgrel=1
pkgdesc="$pkgdesc"
arch=('x86_64' 'aarch64')
url="$repo"
license=('MIT')
provides=('$package')
conflicts=('$package')
source_x86_64=("\$pkgname-\$pkgver-x86_64.tar.gz::$url_x86")
source_aarch64=("\$pkgname-\$pkgver-aarch64.tar.gz::$url_arm")
sha256sums_x86_64=('$sha_x86')
sha256sums_aarch64=('$sha_arm')

package() {
  local dir="\$srcdir/$package-$version-\$( [ "\$CARCH" = x86_64 ] && echo x86_64-unknown-linux-gnu || echo aarch64-unknown-linux-gnu )"
  install -Dm755 "\$dir/$package" "\$pkgdir/usr/bin/$package"
  install -Dm644 "\$dir/LICENSE" "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
  install -Dm644 "\$dir/README.md" "\$pkgdir/usr/share/doc/\$pkgname/README.md"
}
EOF

cat > "$outdir/.SRCINFO" <<EOF
pkgbase = $pkgname
	pkgdesc = $pkgdesc
	pkgver = $version
	pkgrel = 1
	url = $repo
	arch = x86_64
	arch = aarch64
	license = MIT
	provides = $package
	conflicts = $package
	source_x86_64 = $pkgname-$version-x86_64.tar.gz::$url_x86
	sha256sums_x86_64 = $sha_x86
	source_aarch64 = $pkgname-$version-aarch64.tar.gz::$url_arm
	sha256sums_aarch64 = $sha_arm

pkgname = $pkgname
EOF
