#!/usr/bin/env bash
# Render a Homebrew formula for a released binary onto stdout.
#
#   render-formula.sh <package> <version> <tag> <artifact-dir>
#
# <artifact-dir> is the downloaded release artifacts; the per-platform sha256
# values are read from the .sha256 files built alongside each tarball, so the
# formula can never disagree with what was actually uploaded.
set -euo pipefail

package=${1:?package}
version=${2:?version}
tag=${3:?tag}
artifacts=${4:?artifact directory}
shift 4
# Every binary the tarball carries. The clients spawn nitsd, so installing only
# the headline binary yields a formula whose `--version` passes and whose first
# real command fails.
binaries=("$@")
[ ${#binaries[@]} -gt 0 ] || binaries=("$package" nitsd)

repo=https://github.com/JonoPrest/nits

# Homebrew class names are the CamelCase of the formula name.
class=$(echo "$package" | awk -F- '{for (i=1;i<=NF;i++) printf toupper(substr($i,1,1)) substr($i,2); print ""}')

# sha256_for <target> — the checksum recorded for that platform's tarball.
sha256_for() {
  local file
  file=$(find "$artifacts" -name "$package-$version-$1.tar.gz.sha256" -print -quit)
  [ -n "$file" ] || { echo "no checksum for $1 in $artifacts" >&2; exit 1; }
  awk '{print $1}' "$file"
}

url_for() { echo "$repo/releases/download/$tag/$package-$version-$1.tar.gz"; }

case $package in
  nits)     desc="Daemon-backed code review tool where nits stick to content, not diffs" ;;
  nitsd)    desc="Nits code-review daemon" ;;
  nits-mcp) desc="MCP stdio server for the Nits code-review daemon" ;;
  *)        echo "unknown package $package" >&2; exit 1 ;;
esac

cat <<EOF
# Generated by scripts/render-formula.sh — do not edit by hand.
class $class < Formula
  desc "$desc"
  homepage "$repo"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "$(sha256_for aarch64-apple-darwin)"
    end
    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "$(sha256_for x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "$(sha256_for aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "$(url_for x86_64-unknown-linux-gnu)"
      sha256 "$(sha256_for x86_64-unknown-linux-gnu)"
    end
  end

  def install
$(for b in "${binaries[@]}"; do echo "    bin.install \"$b\""; done)
  end

  test do
    assert_match "$version", shell_output("#{bin}/$package --version")
$(case $package in
nits) cat <<'TEST'
    # A command that actually starts and connects to the daemon. `--version`
    # and `daemon status` both pass without nitsd installed — only something
    # reaching ensure_daemon catches a client shipped without it.
    ENV["NITS_DATA_DIR"] = testpath/"data"
    ENV["NITS_CONFIG"]   = testpath/"config.toml"
    system bin/"nits", "workspace", "list"
    system bin/"nits", "daemon", "stop"
TEST
;;
nits-mcp) cat <<'TEST'
    # nits-mcp is a stdio MCP server with no subcommands, so a CLI-shaped
    # smoke test would fail on argument parsing. Drive the protocol instead:
    # the initialize result names the daemon it connected to, and without
    # nitsd installed this returns a JSON-RPC error rather than a result.
    ENV["NITS_DATA_DIR"] = testpath/"data"
    ENV["NITS_CONFIG"]   = testpath/"config.toml"
    req = <<~JSON
      {"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"brew-test","version":"0"}}}
    JSON
    out = pipe_output(bin/"nits-mcp", req)
    assert_match "Connected to nitsd", out
TEST
;;
esac)
  end
end
EOF
